### ISSUE TITLE
Add me as a collaborator!

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/everyone-august-2016#1]
Leave a comment on this issue so you can be added as a collaborator and take part in the activities!

**Comment by shadow247** [comment]
hi

**Comment by rahuuul7** [comment]
hi

**Comment by rwim2** [comment]
hi

**Comment by MrRobot1991** [comment]
Hola!

**Comment by khallai** [comment]
hello

**Comment by ravno** [comment]
me too =)

**Comment by bachkukkik** [comment]
hi there

**Comment by seaswaran** [comment]
Hi

**Comment by Rondieli** [comment]
comment

**Comment by howehcu** [comment]
Add me please

**Comment by hflora** [comment]
hi

**Comment by jasonmowery** [comment]
hola

**Comment by metajemo** [comment]
add me as a collaborator

**Comment by randy-exclaim** [comment]
wah hoo!

**Comment by stsree** [comment]
Add me.

**Comment by unrestrainfly** [comment]
ni hao

**Comment by JohnDeans** [comment]
Hi

**Comment by zorroborg** [comment]
pls add me Thanks

**Comment by ghost** [comment]
Please add me as a collaborator

**Comment by exclaimer** [comment]
hello

**Comment by desireedickerson** [comment]
hi - add plz

**Comment by bmccd** [comment]
Hey

**Comment by pmoag** [comment]
hELLO

**Comment by fjmurray** [comment]
👍

**Comment by TedSpinks** [comment]
hello

**Comment by sergii-van** [comment]
me too

**Comment by iamanushil** [comment]
hello add me as collaborator

**Comment by ankuskum** [comment]
Hello

**Comment by saurabhmicrosoft** [comment]
Hi

**Comment by unrestrainfly** [comment]
hi

**Comment by smurugesan2016** [comment]
hi

**Comment by cardanid** [comment]
Hi

**Comment by githubteacher** [comment]
:tada: @shadow247, @rahuuul7, @rwim2, @MrRobot1991, @khallai, @ravno, @bachkukkik, @seaswaran, @Rondieli, @howehcu, @hflora, @jasonmowery, @metajemo, @randy-exclaim, @stsree, @unrestrainfly, @JohnDeans, @zorroborg, @girarm1, @exclaimer, @desireedickerson, @bmccd, @pmoag, @fjmurray, @TedSpinks, @sergii-van, @hydro69, @ankuskum, @saurabhmicrosoft, @unrestrainfly, and @smurugesan2016 are now  repository collaborators. :balloon:

**Comment by FakeCode** [comment]
intresting, can you pls add me too.

**Comment by nvrdftd** [comment]
Please have me here, thanks.

**Comment by githubteacher** [comment]
:tada: @cardanid, @FakeCode, and @nvrdftd are now  repository collaborators. :balloon:

**Comment by jblattert** [comment]
please add

**Comment by mahesh-s** [comment]
hi there!

**Comment by githubteacher** [comment]
:tada: @jblattert and @mahesh-s are now  repository collaborators. :balloon:

**Comment by noelvaneynde-exclaim** [comment]
please add me

**Comment by githubteacher** [comment]
:tada: @noelvaneynde-exclaim is now a repository collaborator. :balloon:

**Comment by gerbradley** [comment]
Add me please

**Comment by githubteacher** [comment]
:tada: @gerbradley is now a repository collaborator. :balloon:

**Comment by bhatnasa** [comment]
Add me please

**Comment by githubteacher** [comment]
:tada: @bhatnasa is now a repository collaborator. :balloon:

**Comment by crowvoorhees** [comment]
:smile:

**Comment by githubteacher** [comment]
:tada: @crowvoorhees is now a repository collaborator. :balloon:
