### ISSUE TITLE
githubteacher-tampa

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/everyone-august-2016#9]
### Steps
- [x] Create an Issue
- [x] Create a branch
- [x] Add a file
- [x] Create a commit
- [x] Open a PR (Pull Request)
- [x] Discuss the PR 
- [x] Merge the PR

@brianamarie  how does this 👀?

**Comment by brianamarie** [comment]
@githubteacher 👍 Looks good!

**Comment by githubteacher** [comment]
@brianamarie I think I'm good to close this issue!

**Comment by brianamarie** [comment]
Woohoo! Close it out. 👍
